# Generated by Django 3.0.1 on 2019-12-29 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROSlug', models.SlugField(blank=True, null=True)),
                ('PROImg', models.ImageField(upload_to='profile/')),
                ('PROGender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=6)),
                ('PROCountry', django_countries.fields.CountryField(max_length=2)),
                ('PROAddress', models.CharField(max_length=100)),
                ('PROUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
